version: "3.7"

networks:
  visitas-net:
    driver: bridge

volumes:
  mssql-vol:

services:
  # data:
  #   build: ../visitas.net/VisitasDataService
  #   image: phinoppix/visitas-backend
  #   environment:
  #     ASPNETCORE_URLS: "https://+;http://+"
  #     ASPNETCORE_HTTPS_PORT: 5001
  #     ASPNETCORE_Kestrel__Certificates__Default__Password: "ab1Password"
  #     ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/visitas-dev.pfx"
  #   ports:
  #     - "5000:80"
  #     - "5001:443"
  #   volumes:
  #     - ${HOME}/.aspnet/https:/https/
  #   container_name: visitas-dev-container

#  db:
#    build: ./postgresql
#    image: phinoppix/visitas-db-service
#    restart: always
#    container_name: visitas-dev-container
#    volumes:
#      - ${HOME}/dockerized-databases/postgres/visitas:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    networks:
#      - visitas-net

#  # Adminer loaded for diagnosing Postgres container and to make
#  # sure the bridge network is configured properly.
#  # http://localhost:8080/
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"
#    networks:
#      - visitas-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: visitas-dev-container
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Visitas!2020
      MSSQL_PID: Express
    networks:
      - visitas-net
    ports:
      - "1433:1433"
    volumes:
      - mssql-vol:/var/opt/mssql
