// export const TERRITORY_TABLE_CODE = 1;
// export const TERRITORY_TABLE_ADDRESSES = 2;
// export const TERRITORY_TABLE_CHECKEDOUT1 = 4;
// export const TERRITORY_TABLE_CHECKEDOUT2 = 8;
// export const TERRITORY_TABLE_CHECKEDOUT3 = 16;
export const TERRITORY_TABLE_CHECKEDOUTBY = 32;
export const TERRITORY_TABLE_EDITOR = 64;
export const TERRITORY_TABLE_ALLCOLUMNS = 2**7-1;